server:
  port: 8004

spring:
  application:
    name: payment-service
  #zk配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/lcc_micro_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# actuator暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'