server:
  port: 9001
spring:
  application:
    name: springcloud-config-center-github
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liangchichang/micro-services-property-center.git
          username: liangchichang
          password: a82433796
          search-paths:
            - micro-services-property-center
          default-label: master
eureka:
  instance:
    instance-id: config-center-9001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetchRegistry: false
    service-url:
      defaultZone: http://lcc-eureka-6001.com:6001/eureka/,http://lcc-eureka-6002.com:6002/eureka/,http://lcc-eureka-6003.com:6003/eureka/
