server:
  port: 8001

spring:
  application:
    name: payment_service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/lcc_micro_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.lcc.cloud.domain    # 所有实体别名类所在包

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    #    hostname: eureka7001.com #eureka服务端的实例名称
    hostname: localhost #eureka服务端的实例名称
    port: 6001
  client:
    service-url:
      #集群指向其它eureka
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机就是7001自己
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    #server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000