spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/lcc_micro_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    instance-id: payment8002
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://lcc-eureka-6001.com:6001/eureka/,http://lcc-eureka-6002.com:6002/eureka/,http://lcc-eureka-6003.com:6003/eureka/
    #server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000